// Import review JSON items generated by ViFood-KG-Builder.
// ViFood-KC is the source graph. Run this only against ViFood-KG.
// Scope: Ingredient/Additive/Nutrient + WikiProfile + WikiSection only.
// Parameter: $items = payload.items from data/output/wiki_*.json

CREATE CONSTRAINT wiki_profile_id IF NOT EXISTS
FOR (profile:WikiProfile)
REQUIRE profile.id IS UNIQUE;

CREATE CONSTRAINT wiki_section_id IF NOT EXISTS
FOR (section:WikiSection)
REQUIRE section.id IS UNIQUE;

UNWIND $items AS item
CALL {
  WITH item
  WITH item WHERE item.entity_type = 'ingredient'
  MERGE (entity:Ingredient {id: item.entity_id})
  SET entity += coalesce(item.source_entity, {})
  RETURN entity
  UNION
  WITH item
  WITH item WHERE item.entity_type = 'additive'
  MERGE (entity:Additive {id: item.entity_id})
  SET entity += coalesce(item.source_entity, {})
  RETURN entity
  UNION
  WITH item
  WITH item WHERE item.entity_type = 'nutrient'
  MERGE (entity:Nutrient {id: item.entity_id})
  SET entity += coalesce(item.source_entity, {})
  RETURN entity
}
MERGE (profile:WikiProfile {id: item.wiki_profile.id})
SET profile += item.wiki_profile
MERGE (entity)-[:HAS_WIKI_PROFILE]->(profile)
WITH profile, item
UNWIND item.wiki_sections AS sectionData
MERGE (section:WikiSection {id: sectionData.id})
SET section.title = sectionData.title,
    section.content = sectionData.content,
    section.section_type = sectionData.section_type,
    section.status = sectionData.status,
    section.order = sectionData.order
MERGE (profile)-[:HAS_SECTION {order: sectionData.order}]->(section);
